### ISSUE TITLE
Utsatt oppgave i syfoinntektsmelding feiler ved: java.util.NoSuchElementException: List is empty.

### ISSUE THREAD

**Issue by maccyber** [navikt/syfoinntektsmelding#253]
Se [loggen](https://logs.adeo.no/goto/d826ba99e6590943543154aca3e36e08)

Det gjelder en bakgrunnsoppgave som skal opprette oppgave i GoSys for en utsatt oppgave med tilstand forkastet.

Feilen ble innført ved #247. Se [UtsattOppgaveService -> opprettOppgaveIGosys](https://github.com/navikt/syfoinntektsmelding/blob/master/src/main/kotlin/no/nav/syfo/utsattoppgave/UtsattOppgaveService.kt#L99) og [InntektsmeldingRepository -> findByArkivReferanse](https://github.com/navikt/syfoinntektsmelding/blob/master/src/main/kotlin/no/nav/syfo/repository/InntektsmeldingRepository.kt#L85)

Feiler ved at oppslag mot inntektsmeldingtabellen med arkivreferanse gir en tom liste, da den forventer et resultat.
Jobben har ikke tilknyttet en inntektsmelding i inntektsmelding tabllen.

```sql
SELECT * from inntektsmelding data ->> 'arkivreferanse' = 'AR416981281'
-- Ingen rader
```

arkivreferanse er satt i raden for utsatt_oppgave.

Vi må finne ut hvorfor inntektsmelding ikke blir lagret i tabellen. Se [pull request](https://github.com/navikt/syfoinntektsmelding/pull/254).

```
Jobb 44f42eea-7937-4c96-b746-8b3cae9a46e7 feilet, forsøker igjen 2022-02-21T20:33:09.381981.
```

Stacktrace:
```
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:212)
	at no.nav.syfo.repository.InntektsmeldingRepositoryImp.findByArkivReferanse(InntektsmeldingRepository.kt:85)
	at no.nav.syfo.utsattoppgave.UtsattOppgaveServiceKt.opprettOppgaveIGosys(UtsattOppgaveService.kt:99)
	at no.nav.syfo.utsattoppgave.UtsattOppgaveService.prosesser(UtsattOppgaveService.kt:65)
	at no.nav.syfo.utsattoppgave.FeiletUtsattOppgaveMeldingProsessor.prosesser(FeiletUtsattOppgaveMeldingProsessor.kt:38)
	at no.nav.helse.arbeidsgiver.bakgrunnsjobb.BakgrunnsjobbService.prosesser(BakgrunnsjobbService.kt:109)
	at no.nav.helse.arbeidsgiver.bakgrunnsjobb.BakgrunnsjobbService.doJob(BakgrunnsjobbService.kt:95)
	at no.nav.helse.arbeidsgiver.utils.RecurringJob$scheduleAsyncJobRun$1.invokeSuspend(RecurringJob.kt:26)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

```sql
SELECT * FROM bakgrunnsjobb WHERE jobb_id = '44f42eea-7937-4c96-b746-8b3cae9a46e7';
```

```
type: feilet-utsatt-oppgave
data: {"timeout": null, "dokumentId": "41fa3bde-3d52-4da2-adf1-f7cbe045aa9a", "dokumentType": "Inntektsmelding", "oppdateringstype": "Opprett"}
```

```sql
SELECT * FROM utsatt_oppgave WHERE inntektsmelding_id = '41fa3bde-3d52-4da2-adf1-f7cbe045aa9a'
```

```
tilstand: forkastet
arkivreferanse: ARxxx
```

**Comment by maccyber** [comment]
Lukket pga. vi ikke har opplevde lignende caser igjen
